name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0  # Change this to your Ruby version

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Set up database
      run: |
        bin/rails db:create
        bin/rails db:migrate
      env:
        RAILS_ENV: test

    - name: Run tests
      run: bin/rails test

    - name: Run RuboCop
      run: bundle exec rubocop
